"""empty message

Revision ID: 4c5e95d665cc
Revises: ed54a12666e6
Create Date: 2023-06-22 17:49:25.787151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5e95d665cc'
down_revision = 'ed54a12666e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personnel'], ['personnels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('personnel', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['personnel'], ['personnels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('clients')
    # ### end Alembic commands ###
